[fetch]
overwrite = on
build_epub = off
clean_title = off
illustration = on
batch_size = 20

# e.g. c:\Users\<username>\Downloads
out_dir =

# e.g. c:\Users\<username>\Downloads
epub_out_dir =

[epub]
clean_title = off

xhtml_dir =
out_dir =

[bookmark_update]
overwrite = off
clean_title = on
skip_completed = on
illustration = on

xhtml_dir =
epub_dir =